DROP DATABASE pizza_order;
CREATE DATABASE IF NOT EXISTS pizza_order;
use pizza_order;

CREATE TABLE pizzas(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
pizza_name VARCHAR(50) NOT NULL,
size ENUM('S', 'M', 'L') NOT NULL,
ingredients VARCHAR(500) NOT NULL,
price DOUBLE(5, 2) NOT NULL
);

CREATE TABLE salads(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
salad_name VARCHAR(50) UNIQUE,
ingredients VARCHAR(500) NOT NULL,
price DOUBLE(5, 2) NOT NULL
);

CREATE TABLE drinks(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
drink_type VARCHAR(25),
brand VARCHAR(25),
quantity INT(11) NOT NULL,
price DOUBLE(5, 2) NOT NULL
);

CREATE TABLE users(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
phone VARCHAR(25) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
dateOrder DATETIME DEFAULT NOW()
);

CREATE TABLE admins(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
adminName VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
phone VARCHAR(25) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
dateOrder DATETIME DEFAULT NOW()
);

CREATE TABLE orders(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
products VARCHAR(1000) NOT NULL,
totalPrice DOUBLE(5, 2) NOT NULL,
username VARCHAR(50) NOT NULL,
orderStatus ENUM('Waiting', 'Accepted', 'Delivery') DEFAULT 'Waiting'
);