DROP DATABASE pizza_order;
CREATE DATABASE IF NOT EXISTS pizza_order;
use pizza_order;

CREATE TABLE pizzas(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
pizza_name VARCHAR(50) NOT NULL,
size ENUM('S', 'M', 'L') NOT NULL,
ingredients VARCHAR(255) NOT NULL,
price DOUBLE NOT NULL
);

CREATE TABLE salads(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
salad_name VARCHAR(50) UNIQUE,
ingredients VARCHAR(255) NOT NULL,
price DOUBLE NOT NULL
);

CREATE TABLE drinks(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
drink_type VARCHAR(50),
brand VARCHAR(25),
quantity INT(11) NOT NULL,
price DOUBLE NOT NULL
);

CREATE TABLE users(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
phone VARCHAR(25) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE admins(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
adminName VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
phone VARCHAR(25) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE orders(
id INT(11) PRIMARY KEY AUTO_INCREMENT,
pizza_id INT(11),
CONSTRAINT FOREIGN KEY(pizza_id) REFERENCES pizzas(id)
ON DELETE SET NULL ON UPDATE CASCADE,
salad_id INT(11),
CONSTRAINT FOREIGN KEY(drink_id) REFERENCES drinks(id)
ON DELETE SET NULL ON UPDATE CASCADE,
drink_id INT(11),
CONSTRAINT FOREIGN KEY(salad_id) REFERENCES salads(id)
ON DELETE SET NULL ON UPDATE CASCADE,
user_id INT(11),
CONSTRAINT FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE,
orderStatus ENUM('Waiting', 'Cooking', 'Delivery') DEFAULT 'Waiting'
);